const productos = [
    {
        id: 1,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
        stock: 10,
    },
    {
        id: 2,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 3,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 4,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 5,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 6,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 7,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 8,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
    {
        id: 9,
        nombre: "Aloe Vera",
        imagen: "",
        descripcion: "",
        precio: "10€",
    },
];
